/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: Problem 002: 4613732
*/

#include <iostream>
using namespace :: std;

int main(){
	long fib1 = 1;
	long fib2 = 2;
	long fib3 = 0;
	long sum = 0;
	while(fib3 <= 4000000){
		fib3 = fib1 + fib2;
		fib1 = fib2;
		fib2 = fib3;
		if(fib3%2==0){sum += fib3;}
	}
	cout << "Result is " << sum + 2 << endl;
	return 0;
}
